<?php
$this->headTitle('All finds recorded in the Parliamentary constituency of '.$this->constituency);
$this->MetaBase('This page lists all objects recorded by the Scheme in the Parliamentary constituency of '.$this->constituency,'archaeology','finds,found in,constituency,archaeology,portable antiquities,' . $this->constituency);
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
$this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {

 $('a[rel*=lightbox]').lightBox()
    })
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<h2>Finds within constituency of <?php echo $this->escape($this->constituency);?></h2>
<div class="row-fluid">
<?php if ($this->finds): ?>
    <div class="stripeMe">
        <?php echo $this->partialLoop('partials/database/findRecordList.phtml',$this->finds);?>
    </div>
<?php else:?>
    <p>No records are available.
<?php endif; ?>
        <?php
echo $this->facetCreator($this->facets);
?>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>

