<?php
 $this->jQuery()->addJavascriptFile($this->baseUrl()
    . '/js/JQuery/jQueryLinkedSelect.js',
    $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
    . '/js/JQuery/coinslinkedselect.js',
    $type='text/javascript');
    ?>

<h2>Add numismatic data</h2>
<p><a class="btn btn-success btn-large" href="<?php echo $this->url(array('module' => 'database','controller' => 'coins','action' => 'add','copy' => 'last'),null,false);?>" title="Autofill form fields from last record you created" id="populate" accesskey="c">Copy last record</a></p>

<?php echo $this->form;?>