<?php
 $this->jQuery()->addJavascriptFile($this->baseUrl()
    . '/js/JQuery/jQueryLinkedSelect.js',
    $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
    . '/js/JQuery/coinslinkedselect.js',
    $type='text/javascript');
    ?>

<h2>Add numismatic data</h2>

<?php $id = Zend_Controller_Front::getInstance()->getRequest()->getParam('returnID');?>
<p><a class="btn btn-success " href="<?php echo $this->url(array('module' => 'database','controller' => 'coins','action' => 'add','copy' => 'last'),null,false);?>" title="Autofill form fields from last record you created" id="populate" accesskey="c">Copy last record</a> 
<a class="btn btn-success" href="<?php echo $this->url(array('module' => 'database','controller' => 'artefacts','action' => 'record', 'id' => $id),null,false);?>" title="return to the record">Return to record</a></p>
<div class="well"><h3>Annoying reminder: <?php 
$welcome = array(
	'Data in = data out', 
	'Do it right, do it once', 
	'Remember the AD/BC style guide',
	'Does this record follow the PAS recording guide?',
	'If you are not sure, ask a finds adviser',
	'Everything you write is audited and can be requested under Freedom of Information, be sensible',
	'Is the record finished? If so can it be made public?',
	'No abbreviations - stg. l. cuir. etc are banned'
);
echo  $welcome[array_rand($welcome)];

?></h3></div>
<?php echo $this->form;?>
<?php $this->jQuery()->javascriptCaptureStart();?>
$(document).ready(function() {
       // focus on the first text input field in the first field on the page
        $("input[type='select']:first", document.forms[0]).focus();
    });
<?php $this->jQuery()->javascriptCaptureEnd();?>