<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl() 
    . '/js/JQuery/jQueryLinkedSelect.js',  $type='text/javascript'); 
    $this->jQuery()->addJavascriptFile($this->baseUrl() 
    . '/js/JQuery/coinslinkedselect.js',
    $type='text/javascript'); 
?>
<h2>Edit this numismatic entry</h2>
<?php $id = Zend_Controller_Front::getInstance()->getRequest()->getParam('returnID');?>
<p><a class="btn btn-success" href="<?php echo $this->url(array('module' => 'database','controller' => 'artefacts','action' => 'record', 'id' => $id),null,false);?>" title="return to the record">Return to record</a></p>
<?php 
$this->form->setLegend('Edit data');
echo $this->form;?>