<?php $this->headTitle('Our database is offline');?>
<h1><?php echo $this->title();?></h1> 

<p>We're doing some technological refreshment works. We'll be offline for 2 days probably.</p>
<div style="margin-left:90px; margin-right:20px">
<img src="http://farm9.staticflickr.com/8427/7757131284_a38bd4f9e9_z.jpg" alt="Tour party"  />
</div>
<p>The image above is a CC licenced image by <a href="http://www.flickr.com/photos/merryjack/" >J.C.Merriman</a> and shows a tour group being shown round the amazing lego colosseum at the Nicholson Museum, Sydney Australia.<br />This year they have an <a href="http://www.smh.com.au/photogallery/entertainment/art-and-design/lego-model-of-the-acropolis-20130709-2poga.html">Acropolis installation</a>.</p>
