

<h1>An error has occurred</h3>

<p>We're aware this is frustrating and the system has flagged this via email to us.</p>
<p>For your reference, quote error code: <strong><?php echo $this->code;?></strong> and the following message if you contact us:</p>
<div class="well hero-unit"><h2><?php echo $this->code;?>: <?php echo $this->message ?></h2></div>

    <h3>Exception information:</h3>
    <p>
        <b>Message:</b>
		<?php echo $this->exception->getMessage();
		$this->actionerrors()?>
    </p>
<img src="<?php echo $this->serverUrl();?>/assets/indy.jpg">
<p><a href="http://www.flickr.com/photos/donsolo/2354816855/">Indy helps out with the egg hunt</a>: a photo by Don Solo on Flickr.</p>



<div class="row-fluid">

		  <ul id="tab" class="nav nav-tabs">
            <li class="active"><a href="#request" data-toggle="tab">Request</a></li>
            <li><a href="#trace" data-toggle="tab">Stack trace</a></li>
            <li><a href="#compiled" data-toggle="tab">Compiled Stack trace</a></li>
          </ul>
          
          <div id="myTabContent" class="tab-content">
            
            <div class="tab-pane fade in active" id="request">
			<h3>Stack trace:</h3>
    		<p><?php echo $this->exception->getTraceAsString(); ?></p>        
			</div>
			
            <div class="tab-pane fade" id="trace">
			<h3>Issuing mints</h3>
    		<h3>Request Parameters:</h3>
    		<p><? var_dump($this->request->getParams()) ?></p>          
			</div>
            
            <div class="tab-pane fade" id="compiled">
            <h3>Compiled stack trace</h3>
            <ul id="related">
			<?php echo $this->compiled;?>
			</ul>
			</div>

		</div>
          </div>