

<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2>

<p><strong><?php echo $this->code;?></strong></p>

    <h3>Exception information:</h3>
    <p>
        <b>Message:</b>
		<?php echo $this->exception->getMessage();
		$this->actionerrors()?>
    </p>
<h3>The PAStexplorers are on the case!</h3>
<img src="<?php echo $this->baseUrl();?>/images/children.png">



<div class="row-fluid">

		  <ul id="tab" class="nav nav-tabs">
            <li class="active"><a href="#request" data-toggle="tab">Request</a></li>
            <li><a href="#trace" data-toggle="tab">Stack trace</a></li>
            <li><a href="#compiled" data-toggle="tab">Compiled Stack trace</a></li>
          </ul>
          
          <div id="myTabContent" class="tab-content">
            
            <div class="tab-pane fade in active" id="request">
			<h3>Stack trace:</h3>
    		<p><?php echo $this->exception->getTraceAsString(); ?></p>        
			</div>
			
            <div class="tab-pane fade" id="trace">
			<h3>Issuing mints</h3>
    		<h3>Request Parameters:</h3>
    		<p><? var_dump($this->request->getParams()) ?></p>          
			</div>
            
            <div class="tab-pane fade" id="compiled">
            <h3>Compiled stack trace</h3>
            <ul id="related">
			<?php echo $this->compiled;?>
			</ul>
			</div>

		</div>
          </div>