<?php

$dom 	  = new DomDocument("1.0", "UTF-8");
$dom->createElement('markers');

$documentNode = $dom->createElement('markers');
$dom->appendChild($documentNode);


foreach($this->results as $result){
    if(!is_null($result['longitude'])){

        if(isset($result['thumbnail'])){
        $url = '/images/thumbnails/';
        $description = '<img src="' . $this->serverUrl() . $url . $result['thumbnail'] . '.jpg" style="float:right;"/>';
        }
        $description .= '<h3>';
        $description .= $result['old_findID'];
        $description .= '</h3>';
        $description .= $this->purify($this->ellipsisstring($result['description'],500));

        $description .= '<p>Record Url: <a href="' . $this->serverUrl() . '/database/artefacts/record/id/' . $result['id'] . '">';
        $description .= $this->serverUrl() . '/database/artefacts/record/id/' . $result['id'] . '</a></p>';
	$marker = $dom->createElement('marker');
	$marker->setAttribute('lat', $result['latitude']);
        $marker->setAttribute('lng', $result['longitude']);
        $marker->setAttribute('content', $description);
	$documentNode->appendChild( $marker );
    }
}


$xmlData  = $dom->saveXML();
echo $xmlData;