<?php
$pdf = new Pas_Pdf_Document($this->filename,$this->path);
$page = new Pas_Pdf_Page(Zend_Pdf_Page::SIZE_A4_LANDSCAPE);
$font = Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_HELVETICA);

  // set font
  $page->setFont($font, 24);

$table = new Pas_Pdf_Table(8);
$cols = array();

foreach($this->nms as $norfolk => $v){
    $row = new Pas_Pdf_Table_Row();
        $col = new Pas_Pdf_Table_Column();
      $col->setText($v);
      $cols[] = $col;
    $row->setColumns($cols);
    $row->setFont($font, 14);
    $row->setBorder(Pas_Pdf::TOP, new Zend_Pdf_Style());
    $row->setBorder(Pas_Pdf::BOTTOM, new Zend_Pdf_Style());
    $row->setBorder(Pas_Pdf::LEFT, new Zend_Pdf_Style());
    $row->setCellPaddings(array(10,10,10,10));
}

    $table->addRow($row);
    $page->addTable($table, 0, 0);

  // add page to document
  $pdf->addPage($page);

  // save as file
  $pdf->save();

?>
