  <div class="modal-header">
    <a class="close" data-dismiss="modal">x</a>
    <h3>Cite this record</h3>
  </div>
  <div class="modal-body"><p>This record can be cited in the Harvard bibliographic style using the text below:</p>
<?php echo $this->partialLoop('partials/database/webCiteData.phtml',$this->finds);?>
  </div>
  <div class="modal-footer">
    <a href="#" data-dismiss="modal" class="btn">Close</a>
  </div>