<?php
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css');#
$this->headTitle('All finds created by me');

?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox()
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>

<h2>All finds and coins recorded by <?php echo $this->fullname();?></h2>

<?php echo $this->loggedinlinks();?>

<?php if($this->params):?>
<?php echo $this->SearchParams($this->params);?>
<?php endif;?>

<?php echo $this->form;?>
<?php
echo $this->facetCreator($this->facets);
?>
<?php if (count($this->results)): ?>
<div class="stripeMe">
        <?php echo $this->partialLoop('partials/database/findRecordList.phtml',$this->results);?>
    </div>
<?php else:?>
    <p>You have not recorded any objects.</p>
<?php endif; ?>



<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>