<?php
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox()
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>


<h2>All images added by me</h2>
<?php echo $this->form;?>

<?php if ($this->results): ?>
<div class="row-fluid ">
    <div class="span10">
    <ul class="thumbnails">
<?php echo $this->partialLoop('partials/database/myimagesList.phtml',
        $this->results);?>
    </ul>
    </div>
<?php
echo $this->facetCreator($this->facets);
?>
</div>
<?php echo $this->paginationControl($this->paginator, 'Elastic',
        'structure/pagination.phtml'); ?>

<?php else:?>
<p>You have added no images to our database.</p>
<?php endif; ?>
