<?php
$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/autocompleteinit.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
	$this->headTitle('All images created by me');
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox()
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php $this->headTitle('All finds created by ' . $this->Institution($this->inst)); ?>
<h2>All finds and coins recorded by institution: <?php echo $this->Institution($this->inst);?></h2>
<?php echo $this->loggedinlinks();?>
<?php if($this->params):?>
<?php echo $this->SearchParams($this->params);?>
<?php endif;?>
<?php echo $this->form;?>
<div class="row-fluid">
		
    	<?php if ($this->results): ?>
		<div class="span9">
        <?php echo $this->partialLoop('partials/database/findRecordList.phtml',$this->results);?>
        </div>
        <div class="span3">
		<p><a class="btn btn-small" href="<?php echo $this->url(array('action' => 'institutionmap'),null,false);?>" title="Map these records">Map these finds <i class="icon-map-marker"></i></a></p>
        <p>Total results available: <?php echo $this->paginator->getTotalItemCount();?></p>
        <?php echo $this->facetCreator($this->facets); ?>
		</div>
        <?php else:?>
    
    	<p>No records are available.

        <?php endif; ?>
        
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>


