<?php
$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/autocompleteinit.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
	$this->headTitle('All images created by me');
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox()
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php $this->headTitle('All finds created by ' . $this->Institution($this->inst)); ?>
<h2>All finds and coins recorded by institution: <?php echo $this->Institution($this->inst);?></h2>
<?php echo $this->loggedinlinks();?>
<?php if($this->params):?>
<?php echo $this->SearchParams($this->params);?>
<?php endif;?>
<?php echo $this->form;?>
<?php
echo $this->facetCreator($this->facets);
?>
<div id="findsList">
<?php if (count($this->results)): ?>
<div>
        <?php echo $this->partialLoop('partials/database/findRecordList.phtml',$this->results);?>
    </div>
<?php endif; ?>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
