<?php
if ($d->get('dbpediaowl:thumbnail')){
		$html .= '<a href="' . $d->get('foaf:depiction') . '" rel="lightbox"><img src="' ;
		$html .= $d->get('dbpediaowl:thumbnail');
		$html .= '" class="pull-right"/></a>';
		}
		$html .= '<ul>';
		$html .= '<li>Preferred label: ' . $d->label(self::LANGUAGE) . '</li>';
		$html .= '<li>Geo coords: ' . $d->get('geo:lat') . ',' . $d->get('geo:long') . '</li>';
		$html .= '<li>Definition: ' . $d->get('dbpediaowl:abstract', 'literal', self::LANGUAGE) . '</li>';
		if($d->get('dbpediaowl:elevation')){
		$html .= '<li>Elevation: ' . $d->get('dbpediaowl:elevation') . ' (Max: ' . $d->get('dbpediaowl:maximumElevation') . ' Min: ' . $d->get('dbpediaowl:minimumElevation') . ')</li>';
		}
		$html .= '</ul>';