<?php 

$this->headTitle('Details for issuing mint located at ' . $this->name);
$this->headMeta('Full details for issuing  mint at '. $this->name 
        . ' describing location and recent examples. ','description')
->headMeta('CC NC-SA-BY','dc.rights')
->headMeta('The Portable Antiquities Scheme','dc.publisher')
->headMeta('Daniel Pett','dc.creator');

?>

<h2>The <?php echo $this->escape($this->name);?> mint</h2>

<p>

<?php if(!is_null($this->name)):?>
Mint: <span property="skos:prefLabel"><?php echo $this->escape($this->name);?></span> <br />
<?php endif;?>

<?php if(!is_null($this->abbrev)):?>
Abbreviation: <?php echo $this->abbrev;?>
<?php endif;?>

</p>

<?php if(!is_null($this->description)):?>
<span property="skos:definition"><?php echo $this->description;?></span>
<?php endif;?>
<h3>Geographical entities</h3>
<?php if(!is_null($this->latitude)):?>
<p>Geo location: <span property="gml:pos"><?php echo $this->escape($this->latitude);?>, <?php echo $this->escape($this->longitude);?></span></p>
<?php endif;?>
<?php if(!is_null($this->pleiadesID)):?>
<p><a property="skos:related" resource="http://pleiades.stoa.org/places/<?php echo $this->pleiadesID;?>" href="http://pleiades.stoa.org/places/<?php echo $this->pleiadesID;?>">View on Pleiades</a></p>
<?php endif;?>

<?php if(!is_null($this->pasID)):?>
<p>View <a href="<?php echo $this->url(array(
    'module'=>'database',
    'controller' => 'search',
    'action'=>'results', 
    'mint'=>$this->pasID),
        null,true);?>" title="View all records">all coins recorded</a>, 
        which are attributed to <?php echo $this->escape($this->name);?>.
</p>
<?php endif;?>
