<?php
$this->headTitle('Add a findspot');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jQueryLinkedSelect.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/coinslinkedselect.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/linkedinit.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/iacoinslinkedinit.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
	->appendStylesheet($this->baseUrl().'/css/ui.datepicker.css');
		$front = Zend_Controller_Front::getInstance()->getRequest();
	$copy = $front->getParam('copy');
	if(!is_null($copy)){
		$this->headTitle(' copied from last record');
	}
?>
<h2><?php echo $this->title();?></h2>
<?php $id = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');?>
<p><a href="<?php echo $this->url(array(
	'module' => 'database',
	'controller' => 'findspots',
	'action' => 'add',
	'copy' => 'last'),null,false);?>" title="Autofill form fields from last record you created" 
	id="populate" accesskey="c" class="btn btn-success">Copy last record</a> 
	<a class="btn btn-success" href="<?php echo $this->url(array(
	'module' => 'database',
	'controller' => 'artefacts',
	'action' => 'record', 'id' => $id),null,true);?>" title="return to the record">Return to record</a></p>
	<div class="well"><h3>Annoying reminder: <?php 
$welcome = array(
	'Data in = data out', 
	'Do it right, do it once', 
	'Does this record follow the PAS recording guide?',
	'If you are not sure, ask a finds adviser',
	'Everything you write is audited and can be requested under Freedom of Information, be sensible',
	'Is the record finished? If so can it be made public?',
	'Have you got the grid reference? If not the record is not useful for research',
	'Have you filled in all the details for the place of discovery? Region, County, District, Parish',
	'Hide the find spot by using known as, but do you really need to?'
);
echo  $welcome[array_rand($welcome)];

?></h3></div>
<?php
echo $this->form;
?>
<?php $this->jQuery()->javascriptCaptureStart();?>
$(document).ready(function() {
       // focus on the first text input field in the first field on the page
        $("input[type='select']:first", document.forms[0]).focus();
    });
<?php $this->jQuery()->javascriptCaptureEnd();?>