<?php
$this->headTitle('Edit a findspot');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.chained.remote.min.js', $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/bootstrap-typeahead.js', $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/bootstrap-select.min.js', $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/typeaheads/landowner.js', $type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap-select.min.css', $type='screen');
?>


<?php 
$this->FindSpotEditCheck($this->findspot->old_findspotid,$this->findspot->createdBy);
?>

<h2><?php echo $this->title();?></h2>
<?php $id = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');?>

<p><a class="btn btn-success" href="<?php echo $this->url(array('module' => 'database','controller' => 'artefacts','action' => 'record', 'id' => $id),null,false);?>" title="return to the record">Return to record</a></p>

<?php 
echo $this->form;
?>

<?php $this->jQuery()->javascriptCaptureStart();?>
$(document).ready(function() {
 		
		// focus on the first text input field in the first field on the page
		$("input[type='select']:first", document.forms[0]).focus();
		
		//Reformat the selects
		$('.selectpicker').selectpicker();
       
		//Chain the region to county
		$("#regionID").remoteChained("#county", "/ajax/osregionsbycounty/");
       
		//Chain district to county	
		$("#district").remoteChained("#county", "/ajax/osdistrictsbycounty/");
       
		//Chain parish to district
		$("#parish").remoteChained("#district", "/ajax/osparishesbydistrict/");
      
      	//Chain landuse to specific landuse
		$("#landusecode").remoteChained("#landusevalue", "/ajax/landusecodes/");
      	
      	//Refresh the options of the select
		$(".selectpicker").change(function(){
        $('.selectpicker').selectpicker('refresh');
      	});
      	
    });
<?php $this->jQuery()->javascriptCaptureEnd();?>