<?php $this->headMeta('All comments entered on our database in reverse chronological order','description');
$this->headTitle('Published comments on our database');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript');

?>
<h2>Comments on records</h2>
<div class="row-fluid">
<?php
if($this->comments):?>
	<?php echo $this->partialLoop('partials/database/commentsonfinds.phtml',$this->comments);?>
</div>
<div class="row-fluid">
<?php echo $this->paginationControl($this->comments, 'Sliding', 'structure/pagination.phtml'); ?>
</div>

<?php else:?>
<p>There are no comments available at the moment.</p>
<?php endif;?>


<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
 $('a[rel*=lightbox]').lightBox()
 });
<?php $this->jQuery()->javascriptCaptureEnd() ?>