<div typeof="pas:record" about="[<?php echo $this->old_findID;?>]" class="row span8 well">



    <div> <?php if(isset($this->thumbnail)):?>
     <?php
        $path = '/images/thumbnails/';
        $ext = '.jpg';
        list($w,$h) = getimagesize($this->serverUrl() . $path . $this->thumbnail . $ext );
        ?>
    <ul class="thumbnails" style="float:right;">
        <li >
            <div class="thumbnail">
            <img src="/images/thumbnails/<?php echo $this->thumbnail;?>.jpg"
                    alt="Thumbnail image of <?php echo $this->old_findID;?>"
                    width="<?php echo $w;?>" height="<?php echo $h;?>"/>
            </div>
        </li>
    </ul>

	<?php endif;?>
    <p>
    <?php $url = $this->url(array(
    	'module' => 'database',
    	'controller' => 'artefacts',
    	'action' => 'record',
    	'id' => $this->id),
    	'default',true);?>
        Record ID: <a href="<?php echo $url; ?>" title="View details for <?php echo $this->old_findID;?>"><?php echo $this->old_findID;?></a><br />
        Object type: <?php echo $this->escape($this->objecttype);?><br />
        Broad period: <?php echo $this->broadperiod;?><br />
        County: <?php echo $this->county;?><br />
        Workflow stage: <?php echo $this->workflowStatus($this->workflow);?>
        <?php echo $this->workflow($this->workflow);?><br />
        Description: <?php echo $this->ellipsisstring($this->description,600);?><br />

    </p>

    </div>



</div>
