<div typeof="pas:record" about="[<?php echo $this->old_findID;?>]">
    <div class="thumbnailList dec flow">
        <?php if(isset($this->thumbnail)):?>
        <?php
        $path = '/images/thumbnails/';
        $ext = '.jpg';
        list($w,$h) = getimagesize($this->serverUrl() . $path . $this->thumbnail . $ext );
        ?>
	<img src="/images/thumbnails/<?php echo $this->thumbnail;?>.jpg"
             alt="Thumbnail image of <?php echo $this->old_findID;?>"
             width="<?php echo $w;?>" height="<?php echo $h;?>"/>
	<?php endif;?>
    </div>


    <ul>
    <?php $url = $this->url(array(
    	'module' => 'database',
    	'controller' => 'artefacts',
    	'action' => 'record',
    	'id' => $this->id),
    	'default',true);?>
        <li>Record ID: <a href="<?php echo $url; ?>" title="View details for <?php echo $this->old_findID;?>"><?php echo $this->old_findID;?></a></li>
        <li>Object type: <?php echo $this->escape($this->objecttype);?></li>
        <li>Broad period: <?php echo $this->broadperiod;?></li>
        <li>County: <?php echo $this->county;?></li>
        <li>Workflow stage: <?php echo $this->workflowStatus($this->workflow);?>
        <?php echo $this->workflow($this->workflow);?></li>
        <li>Description: <?php echo $this->ellipsisstring($this->description,500);?></li>
    
    </ul>
</div>
