<?php
$config = Zend_Registry::get('config');
$apikey = $config->webservice->googlemaps->apikey;
$this->inlineScript()->appendFile('http://nls.tileserver.com/api.js',$type='text/javascript');
$this->inlineScript()->appendFile('http://maps.googleapis.com/maps/api/js?v=3.8&sensor=true&region=GB&key=' . $apikey,$type='text/javascript');
?>
<h3>Spatial data</h3>
<?php echo $this->FindSpotEditDeleteLink($this->old_findspotid,$this->id,$this->createdBy);?>

<?php if(isset($this->declong) && isset($this->declat)) : ?>
<div id="map">
<noscript><img src="http://maps.google.com/maps/api/staticmap?center=<?php echo $this->declat;?>,
<?php echo $this->declong;?>&zoom=14&size=640x300&maptype=terrain&markers=color:green|label:G|
<?php echo $this->declat;?>,<?php echo $this->declong;?>&sensor=false" />
</noscript>
</div>
<?php
$allowed = array('hero','flos','admin','treasure','research','fa');
$auth = Zend_registry::get('auth');
$identity = $auth->getIdentity();
$role = $identity->role;
if(in_array($role,$allowed)):
?>
<div id="radius">
	<p>
	<a class="btn btn-small btn-success" href="<?php echo $this->url(array(
	'module' => 'database',
	'controller' => 'search',
	'action' => 'results', 
	'lat' => $this->declat, 
	'lon' => $this->declong,
	'd' => '2'),null,true);?>"  
	title="Use the Haversine formula to find adjacent objects">Find objects within 2km 
	radius of this artefact</a>
	</p>
</div>
<?php endif;?>
<?php $this->inlineScript()->captureStart();?>
$(document).ready(function() {

	var osmMapType = new google.maps.ImageMapType({
        getTileUrl: function (coord, zoom) {
            return "http://tile.openstreetmap.org/" +
                zoom + "/" + coord.x + "/" + coord.y + ".png";

        },
        tileSize: new google.maps.Size(256, 256),
        isPng: true,
        alt: "OpenStreetMap layer",
        name: "OSM",
        maxZoom: 18
    });
        
	var myOptions = {
          center: new google.maps.LatLng(<?php echo $this->declat;?>, <?php echo $this->declong;?>),
          zoom: 12,
		  mapTypeControlOptions: {
          mapTypeIds: [
          google.maps.MapTypeId.ROADMAP, 
          google.maps.MapTypeId.HYBRID,
          google.maps.MapTypeId.TERRAIN,
          google.maps.MapTypeId.SATELLITE,
          'OSM'
          ]
    	  },
    	  mapTypeControl: true,
    	  style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
          scaleControl: true,
    	  zoomControl: true,
          mapTypeId: 'OSM',
          scrollwheel: false,
        };
        var map = new google.maps.Map(document.getElementById("map"),
            myOptions);
            map.mapTypes.set('OSM',osmMapType); 
            map.setTilt(45);
        var marker = new google.maps.Marker({
      		position: new google.maps.LatLng(<?php echo $this->declat;?>, <?php echo $this->declong;?>),
      		map: map,
      		animation: google.maps.Animation.DROP,
      		title:"Findspot location",
      		icon: "<?php echo $this->serverUrl();?>/images/logos/museum_archeological.png" 
  		});
  		var parish = new google.maps.KmlLayer('<?php echo $this->serverUrl();?>/kml/parishes/<?php echo strtoupper(str_replace(' ','',$this->parish));?>.kml',
                                                 {preserveViewport: true, suppressInfoWindows: false });
		parish.setMap(map);
		var county = new google.maps.KmlLayer('<?php echo $this->serverUrl();?>/kml/<?php echo strtoupper(str_replace(' ','',$this->county));?>.kml',
                                                 {preserveViewport: true, suppressInfoWindows: false });
		county.setMap(map);

<?php 
	$bbox = new Pas_Geo_BoundBox();
	$d = 5;  // distance
    $path_top_right = $bbox->createPoint($this->declat ,  $this->declong, 45, $d);
    $path_bottom_right = $bbox->createPoint($this->declat ,  $this->declong, 135, $d);
    $path_bottom_left = $bbox->createPoint($this->declat ,  $this->declong, 225, $d);
    $path_top_left = $bbox->createPoint($this->declat ,  $this->declong, 315, $d);
?>
  		
  		 var latLngBounds = new google.maps.LatLngBounds(
          new google.maps.LatLng(<?php echo $path_bottom_left;?>),
          new google.maps.LatLng(<?php echo $path_top_right;?>)
        );
    	map.fitBounds(latLngBounds);
  		google.maps.event.addListener(marker, 'click', toggleBounce);
	
	function toggleBounce() {
		if (marker.getAnimation() != null) {
    		marker.setAnimation(null);
  		} else {
    		marker.setAnimation(google.maps.Animation.BOUNCE);
  		}
  		}
});
<?php $this->inlineScript()->captureEnd();?>
<?php endif;?>
<div class="row-fluid">

<div class="span4">
<h3>Spatial metadata</h3>
<p>
<?php if(!is_null($this->region)) :?>
Region: <?php echo $this->escape(ucwords(strtolower($this->region)));?><br />
<?php endif;?>
<?php if(!is_null($this->county)) :?>
County: <?php echo $this->escape(ucwords(strtolower($this->county)));?><br />
<?php endif;?>
<?php if(!is_null($this->district)) :?>
District: <?php echo $this->escape(ucwords(strtolower($this->district)));?><br />
<?php endif;?>
<?php if(!is_null($this->parish)) :?>
Parish: <?php echo $this->escape(ucwords(strtolower($this->parish)));?>
<?php endif;?>
<?php if(!is_null($this->knownas)) :?>
<br /><span class="knownas">To be known as: <?php echo $this->escape($this->knownas);?></span>
<?php endif;?>
</p>
</div>

<div class="span4">
<?php if(!is_null($this->gridref)): ?>
<h3>Spatial coordinates</h3>
<p>
Grid reference: <?php echo $this->StripGrid($this->gridref);?><br />
<span class="fourfigure">4 Figure: <?php echo $this->fourFigure;?></span><br />
Grid reference source: <?php echo $this->escape($this->source);?><br />
Grid reference accurate to a <?php echo $this->GetAccuracy($this->gridref);?> metre square.<br />
Easting: <?php echo $this->easting;?>  Northing: <?php echo $this->northing;?><br />
Latitude: <?php echo $this->declat;?> Longitude: <?php echo $this->declong;?><br />
1:25K map: <?php echo $this->map25k;?><br />
1:10K map: <?php echo $this->map10k;?>
</p>

</div>

<div class="span4">
<?php echo $this->domesdayNear($this->declat,$this->declong, 2);?>
</div>

</div>

<div class="row-fluid">
<?php echo $this->findSmrs($this->declat,$this->declong);?>
</div>

<div class="row-fluid">

<div class="span4">
<?php
echo $this->findspotGeo($this->woeid,$this->declat,$this->declong);
?>
</div>

<div class="span4">
<?php echo $this->yahooGeoAdjacent($this->woeid);?>
</div>

<div class="span4">
<h3>Discovery metadata</h3>
<p>
<?php if(!is_null($this->method)) :?>
Method of discovery: <?php echo $this->escape($this->method);?>
 <span class="scope">[<a href="<?php echo $this->url(array(
     'module' => 'database',
     'controller'=>'terminology',
    'action'=>'method',
     'id' => $this->discmethod),null,true);?>"
 title="Read scope note for <?php echo $this->method;?>">scope notes</a>]</span><br />
<?php endif;?>

<?php if(!is_null($this->disccircum)) :?>
Discovery circumstances:  <?php echo $this->escape($this->disccircum);?> <br />
<?php endif;?>

<?php if(!is_null($this->curr_loc)) :?>
Current location: <?php echo $this->escape($this->curr_loc);?> <br />
<?php endif;?>

<?php if(!is_null($this->landvalue)) :?>
General landuse: <?php echo $this->landvalue;?>
<span class="scope">[<a href="<?php echo $this->url(array(
    'module' => 'database',
    'controller' => 'terminology',
    'action' => 'landuse',
    'id' => $this->landusevalue)
	,NULL, true);?>" title="View scope notes for <?php echo $this->landvalue;?>">scope notes</a>]
</span><br />
<?php endif;?>

<?php if(!is_null($this->landuse)) :?>
Specific landuse: <?php echo $this->escape($this->landuse);?>
<span class="scope">[<a href="<?php echo $this->url(array(
    'module' => 'database',
    'controller'=>'terminology',
    'action'=> 'landuse',
    'id' => $this->landusecode),null,true);?>"
    title="Read scope note for <?php echo $this->landuse;?>">scope notes</a>]
</span><br/>
<?php endif;?>
</p>
</div>
</div>
<?php endif; ?>


</div>

<div class="row-fluid">
<?php if(!is_null($this->description) && ($this->description != '')):?>
<p>Findspot description: <?php echo $this->description;?></p>
<?php endif;?>

<?php if(!is_null($this->comments) && ($this->comments != '')):?>
<p>Findspot comments: <?php echo $this->comments;?></p>
<?php endif;?>

<?php if(!is_null($this->fullname)):?>
<p>Land is owned by: <?php echo $this->fullname;?></p>
<?php endif;?>
<?php if(!is_null($this->address)):?>
<p>Address: <?php echo $this->escape($this->address);?></p>
<?php  endif;?>
<?php if(!is_null($this->postcode)):?>
<p>Postcode: <?php echo $this->escape($this->postcode);?></p>
<?php  endif;?>
</div>