<?php $this->headTitle('User account public data for '.$this->username);?>
<h2>Public profile for <?php echo $this->username;?></h2>
<div id="gravatar-badge">
<?php
echo $this->gravatar($this->email,array(
		'imgSize' => 30, 
		'defaultImg' => 'http://finds.org.uk/assets/gravatar.png',
        'secure' => true),
	array(
        'class' => 'avatar img-circle stelae ',
        'title' => $this->fullname . '\'s gravatar representation',
        'rating' => 'G',
		'height' => 30,
		'width' => 30));
?>
</div>
<div id="userDetails">
<ul>
<li>Username: <?php echo $this->username;?></li>
<li>Last login: <?php echo $this->timeagoinwords($this->lastLogin);?></li>
<li>Account created: <?php echo $this->timeagoinwords($this->created);?></li>
<li>Number of visits: <?php echo $this->visits;?></li>
</ul>
</div>

<?php
echo $this->UserRecords($this->username);
?>
<?php echo $this->OnlineAccountHtmlPublic($this->id);?>
