<?php
$this->headTitle("Welcome to the Scheme's database");
$this->headMeta('This database is maintained by the Scheme and contains records of archaeological objects found by the public in England and Wales. It is first and foremost a research resource, but it is also a record of our rural archaeological record','description');
$this->headMeta('archaeology,database,England,Wales,discovery,archaeological','dc.keywords');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.js',$type='text/javascript')
 			   ->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinitwww.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/tabs.css')
				 ->appendStylesheet($this->baseUrl().'/css/autocomplete.css');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox()
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php
$config = Zend_Registry::get('config');
$apikey = $config->webservice->googlemaps->apikey;
$this->inlineScript()->appendFile('http://nls.tileserver.com/api.js',$type='text/javascript');
$this->inlineScript()->appendFile('http://maps.googleapis.com/maps/api/js?v=3.8&sensor=true&region=GB&key=' . $apikey,$type='text/javascript');
?>
<?php $this->inlineScript()->captureStart();?>
$(document).ready(function() {

	var osmMapType = new google.maps.ImageMapType({
        getTileUrl: function (coord, zoom) {
            return "http://tile.openstreetmap.org/" +
                zoom + "/" + coord.x + "/" + coord.y + ".png";

        },
        tileSize: new google.maps.Size(256, 256),
        isPng: true,
        alt: "OpenStreetMap layer",
        name: "OSM",
        maxZoom: 18
    });
    
        
	var myOptions = {
          center: new google.maps.LatLng(54,-2),
          zoom: 6,
		  mapTypeControlOptions: {
          mapTypeIds: [
          google.maps.MapTypeId.TERRAIN,
          google.maps.MapTypeId.SATELLITE,
          'OSM'
          ]
    	  },
    	  mapTypeControl: true,
    	  style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
          scaleControl: true,
    	  zoomControl: true,
          mapTypeId: 'OSM',
          scrollwheel: false,
        };
        var map = new google.maps.Map(document.getElementById("map"),
            myOptions);
            map.mapTypes.set('OSM',osmMapType); 
            map.setTilt(45);
        var county = new google.maps.KmlLayer('http://finds.org.uk/database/search/results/note/1/reason/2/format/kml',
                                                 {preserveViewport: true, suppressInfoWindows: false });
		county.setMap(map);    
       
      
});
<?php $this->inlineScript()->captureEnd();?>
<?php
$this->jQuery()->javascriptCaptureEnd();?>
<h2>Welcome to the Scheme's database</h2>

<div class="row-fluid">
	<div id="map" style="min-height:100px; height:250px; margin-bottom:30px;">
	</div>
</div>

<div class="row-fluid">
	<div class="span4">
	<?php 
	echo $this->form; 
	?>
	</div>
	<div class="span8">
	<h2><?php echo number_format($this->counts['0']['c']);?> records of <?php echo number_format($this->counts['0']['q']);?> artefacts</h2>
	</div>
</div>

<div class="row-fluid">
<?php foreach($this->contents as $c) {
echo $c['body'];
}
?>
</div>
