<?php
$this->headTitle("Welcome to the Scheme's database");
$this->headMeta('This database is maintained by the Scheme and contains records of archaeological objects found by the public in England and Wales. It is first and foremost a research resource, but it is also a record of our rural archaeological record','description');
$this->headMeta('archaeology,database,England,Wales,discovery,archaeological','dc.keywords');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.js',$type='text/javascript')
 			   ->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinitwww.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/tabs.css')
				 ->appendStylesheet($this->baseUrl().'/css/autocomplete.css');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',$type='text/javascript');
?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox()
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php
$this->jQuery()->javascriptCaptureEnd();?>
<h2>Welcome to the Scheme's database</h2>

<?php echo $this->form; ?>

<div class="hero-unit span10">
<h2><?php echo number_format($this->counts['0']['c']);?> records of <?php echo number_format($this->counts['0']['q']);?> artefacts</h2>
</div>
<div class="row span12">
<?php foreach($this->contents as $c) {
echo $c['body'];
}
?>
</div>
