<div class="well row-fluid" >
    <div class="span8"><h3>Britain's Secret Treasures on ITV1, ITVHD and ITVplayer</h3>
    <p>From Monday 16th July, ITV1 and subsidiary channels will be featuring archaeological objects found by the British public. Tune in to
    find out about the significance of objects as diverse as slave shackles, Roman cavalry helmets and Bronze Age cups. Presented by Michael Buerk and Bettany
    Hughes, this series will show over 6 nights on prime time ITV slots.</p><p>You can find out more about the series and the objects featured in our dedicated section for this ground <a href="<?php echo $this->url(array('module' => 'secrettreasures'),null,true);?>">breaking series</a> which has been produced in partnership with the Council for British Archaeology and ITN.</p></div>
    <div class="span4"><a href="<?php echo $this->url(array('module' => 'secrettreasures'),null,true);?>"><img  src="<?php echo $this->serverUrl();?>/images/logos/bst.png" alt="Britain's Secret Treasures logo" /></a></div>
</div>