<?php
if (!empty($this->messages[0])) :?>
<?php
$this->jQuery()->javascriptCaptureStart();?>
$(document).ready(function(){
setTimeout(function(){ 
$('#flashmessenger').fadeOut('slow'); }, 8000);
}); 
<?php $this->jQuery()->javascriptCaptureEnd();?>
<div class="alert alert-info" id="flashmessenger">
<a class="close" data-dismiss="alert"><i class="icon-eject"></i></a>
<?php foreach($this->messages as $message):?>
<?php echo $message; ?>
<?php endforeach;?>
</div>
<?php endif;?>
<div class="alert alert-danger">
  <strong>Server outage:</strong> The Scheme's servers are scheduled to be offline on Thursday and Friday whilst new hardware is installed and a move of server farm is implemented.<br />
  Updates can be found via our <a href="http://twitter.com/findsorguk">Twitter</a> and <a href="http://facebook.com/portableantiquitiesscheme">Facebook</a> pages.
</div>