<div class="well">
    <h4>Staffordshire Hoard papers</h4>
    <p>The <a href="<?php echo $this->serverUrl();?>/staffshoardsymposium" title="The hoard papers">Staffordshire Hoard symposium papers</a> have been published for all to access and the <a href="<?php echo $this->serverUrl();?>/staffshoard" title="The old Staffshoard website">old website</a> has
been archived on our site for reference. The hoard's records are being added slowly to the database.</p>

</div>
