<div class="well">
    <h4>Staffordshire Hoard papers</h4>
    <p>The <a href="<?php echo $this->serverUrl();?>/staffshoardsymposium" title="The hoard papers">Staffordshire Hoard symposium papers</a> have been published for all to access and the <a href="<?php echo $this->serverUrl();?>/staffshoard" title="The old Staffshoard website">old website</a> has
been archived on our site for reference. The hoard's records are being added slowly to the database.</p>

</div>
<div >
    
    <a href="http://dayofarchaeology.com"><img src="https://fbcdn-sphotos-a.akamaihd.net/hphotos-ak-ash3/550639_429591427062696_865930474_n.jpg"/></a>
</div>

<div>

   
    <a href="http://pastexplorers.org.uk"><img src="http://farm2.staticflickr.com/1229/858393034_bb2e489d69_m.jpg"/></a>

</div>