<?php
$this->headTitle('Analytics data provided via Google Analytics');
?>
<h2><?php echo $this->title();?></h2>
<img src="<?php echo $this->serverUrl();?>/assets/google-analytics-logo.png" />
<ul>
<?php foreach($this->result as $row): 
echo 'Page views: ' .  number_format($row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_PAGEVIEWS)->value);
echo '<br/>'; 
echo 'Unique pageviews: ' .  $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_UNIQUE_PAGEVIEWS)->value;
echo '<br/>'; 
echo 'Visits: ' .  number_format($row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITS)->value); 
echo '<br/>'; 
echo 'Visitors: ' .  number_format($row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value); 
echo '<br/>'; 
echo 'Time on site: ' .  $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_TIME_ON_SITE)->value; 
endforeach;
?>    
</ul>