<?php $this->headTitle('All messages submitted to the Scheme');?>
<h2>All messages submitted</h2>
<?php if(count($this->messages)):?>
<table class="table table-striped" summary="All messages submitted">
    <caption>All messages</caption>
<thead>
	<tr>
	<th scope="col" id="author" class="manage-column column-author">Author</th>
	<th scope="col" id="comment" class="manage-column column-comment">Comment</th>
	<th scope="col" id="response" class="manage-column column-response">Status</th>
	<th scope="col">Actions</th>
	</tr>

</thead>


<tbody>

<?php echo $this->partialLoop('partials/admin/messages.phtml', $this->messages) ?>

</tbody>

</table>
<?php else:?>
<p>No messages are listed or available to you</p>
<?php endif;?>
<?echo $this->paginationControl($this->messages, 'Sliding', 'structure/pagination.phtml'); ?>

<?php 
$this->inlineScript()->appendFile('/js/bootstrap-modal.js', $type='text/javascript');
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
	$('.overlay').click(function(e) {
    e.preventDefault();
    var href = $(e.target).attr('href');
    if (href.indexOf('#') == 0) {
        $(href).modal('open');
    } else {
        $.get(href, function(data) {
            $('<div class="modal fade" >' + data + '</div>').modal();
        });
    }
});

	}); 
<?php $this->inlineScript()->captureEnd();?>