<?php
$this->headMeta('noodp','robots');
$this->headMeta('BJ0IxlmtPbri25v9zbMgcOFDOBuZmNacd9-friMs1_E','google-site-verification');
$this->jQuery()->addJavascriptFile('/js/bootstrap-carousel.js',$type='text/javascript');
?>


<div class="row-fluid">
    <div ><?php echo $this->partialLoop('partials/content/article.phtml',$this->contents);?></div>

</div>
    
<div class="row-fluid">
<section id="carousel" class="span6">

        <div >

          <div id="myCarousel" class="carousel slide">
            <div class="carousel-inner">
            <div class="item active">
                <img src="http://farm2.staticflickr.com/1301/972857332_792e600300_z.jpg" alt="The Staffordshire Moorlands trulla">
                <div class="carousel-caption">
                  <h4>The Staffordshire Moorlands trulla</h4>
                  <p>The Staffordshire pan is one of the most iconic objects reported to the Scheme.</p>
                </div>
              </div>
              <div class="item">
                <img src="http://farm9.staticflickr.com/8167/7549200844_4e68f22d57_z.jpg" alt="Helen Geake with the North West Essex ring">
                <div class="carousel-caption">
                  <h4>Helen Geake with the North West Essex ring</h4>
                  <p>Helen Geake holds the North West Essex gold ring during the filming of Britain's Secret Treasures.</p>
                </div>
              </div>
              <div class="item">
                <img src="http://farm9.staticflickr.com/8146/7549080550_205c502182_z.jpg" alt="The Hackney hoard">
                <div class="carousel-caption">
                  <h4>The Hackney Hoard</h4>
                  <p>An interesting Treasure case, with a human touch. The Hackney hoard relates to the sad
                  story of the Sulzbacher family</p>
                </div>
              </div>
              <div class="item">
                <img src="http://farm8.staticflickr.com/7251/7549072406_69f42574e4_z.jpg" alt="The magnificent Frome hoard">
                <div class="carousel-caption">
                  <h4>The magnificent Frome hoard</h4>
                  <p>150 kg of Roman coins were found by detectorist Dave Crisp.</p>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
          </div>

        </div>
        
	</section>
	
	<div class=" span6"><h3>Latest news</h3>
        <ul>
        <?php
        echo $this->partialLoop('partials/index/headlines.phtml',$this->news);
        ?>
        </ul>
         <?php echo $this->britainSecretTreasureFront();?>
    </div>
      </div> 
    
    
    <div class="span10">
    <?php echo $this->partialLoop('partials/index/quotes.phtml',$this->quotes);?>
	</div>

	<div id="tweets" class="well span6">
 	<h3>Latest tweets</h3>
    	<?php echo $this->LatestTweets();?>
    <a href="http://twitter.com/findsorguk" title="View our twitter profile"><img class="twitterbird" src="/images/logos/twitter_logo_withbird.png" height="37" width="200" alt="The twitter logo with the tweetie bird" /></a>
    </div>


	<div  class="span4 well">
	<h3>Numismatic guides</h3>
	<p class="indent">Learn about each numismatic study area.</p>
	<ul>
	<li><a href="<?php echo $this->url(array('module' => 'ironagecoins'),null,true);?>" title="Learn about Iron age coins">Iron Age</a></li>
	<li><a href="<?php echo $this->url(array('module' => 'romancoins'),null,true);?>" title="Learn about Roman coins">Roman</a></li>
	<li><a href="<?php echo $this->url(array('module' => 'byzantinecoins'),null,true);?>" title="Learn about Byzantine coins">Byzantine</a></li>
	<li><a href="<?php echo $this->url(array('module' => 'greekromancoins'),null,true);?>" title="Learn about Greek and roman provincial coins">Greek &amp; Roman Provincial</a></li>
	<li><a href="<?php echo $this->url(array('module' => 'earlymedievalcoins'),null,true);?>" title="Learn about Early Medieval coins">Early Medieval</a></li>
	<li><a href="<?php echo $this->url(array('module' => 'medievalcoins'),null,true);?>" title="Learn about Medieval coins">Medieval</a></li>
	<li><a href="<?php echo $this->url(array('module' => 'postmedievalcoins'),null,true);?>" title="Learn about Post medieval coins">Post Medieval</a></li>
	</ul>
	</div>


	<?php $this->jQuery()->javascriptCaptureStart()?>
	$('.myCarousel').carousel({
		interval: 2000
	});
	<?php $this->jQuery()->javascriptCaptureEnd()?>





<?php $this->placeholder('searchForm')->captureStart();?>
<?php
echo $this->form;
?>
<?php $this->placeholder('searchForm')->captureEnd();

