<?php
$this->headMeta('noodp','robots');
$this->headMeta('BJ0IxlmtPbri25v9zbMgcOFDOBuZmNacd9-friMs1_E','google-site-verification');
$this->jQuery()->addJavascriptFile('/js/JQuery/jquery.lightbox.js',$type='text/javascript');
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($) {
$('a[rel*=lightbox]').lightBox()
});


<?php $this->jQuery()->javascriptCaptureEnd() ?>
<div class="container">
<div class="hero-unit">
    <?php echo $this->partialLoop('partials/content/article.phtml',$this->contents);?>
</div>

</div>






<div class="row">
<div  class="span4 well">
<h3>Numismatic guides</h3>
<p class="indent">Learn about each numismatic study area.</p>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'ironagecoins'),null,true);?>" title="Learn about Iron age coins">Iron Age</a></li>
<li><a href="<?php echo $this->url(array('module' => 'romancoins'),null,true);?>" title="Learn about Roman coins">Roman</a></li>
<li><a href="<?php echo $this->url(array('module' => 'byzantinecoins'),null,true);?>" title="Learn about Byzantine coins">Byzantine</a></li>
<li><a href="<?php echo $this->url(array('module' => 'greekromancoins'),null,true);?>" title="Learn about Greek and roman provincial coins">Greek &amp; Roman Provincial</a></li>
<li><a href="<?php echo $this->url(array('module' => 'earlymedievalcoins'),null,true);?>" title="Learn about Early Medieval coins">Early Medieval</a></li>
<li><a href="<?php echo $this->url(array('module' => 'medievalcoins'),null,true);?>" title="Learn about Medieval coins">Medieval</a></li>
<li><a href="<?php echo $this->url(array('module' => 'postmedievalcoins'),null,true);?>" title="Learn about Post medieval coins">Post Medieval</a></li>
</ul>
<span class="twitterbird">
<a href="<?php echo $this->serverUrl();?>/database/artefacts/record/id/198178" title="An early 5th-century gold solidus of Honorius"><img src="/images/logos/solidus.jpg" height="60" width="117" alt="A gold solidus of Honorius" /></a>
<a href="<?php echo $this->serverUrl();?>/database/artefacts/record/id/413297" title="A gold stater of the Atrebates"><img src="/images/logos/stater.jpg" height="60" width="105" alt="A gold stater of the Atrebates" /></a>
</span>
</div>

    <div class="span3 well">
        <h3>Bare stats:</h3>
         <ol><li><?php echo number_format($this->finds['0']['c']);?> records</li><li><?php echo number_format($this->finds['0']['q']);?> objects</li><li><?php echo number_format($this->people['0']['total']);?> people involved</li><li><?php echo number_format($this->users['0']['count']);?> accounts</li>
        </ol>
    </div>

    <div class="span4 well"><h3>Latest news</h3>
        <ul>
        <?php
        echo $this->partialLoop('partials/index/headlines.phtml',$this->news);
        ?>
        </ul>
    </div>

</div>



<div id="quotes">
    <?php echo $this->partialLoop('partials/index/quotes.phtml',$this->quotes);?>
</div>

<div class="row span10 well">
<?php
echo $this->FlickrFront(Zend_Registry::get('config')->webservice->flickr);
?>
</div>

<div class="row">
    <div id="tweets" class="span4 well">
        <h3>Latest tweets</h3>

        <?php echo $this->LatestTweets();?>
        <a href="http://twitter.com/findsorguk" title="View our twitter profile"><img class="twitterbird" src="/images/logos/twitter_logo_withbird.png" height="37" width="200" alt="The twitter logo with the tweetie bird" /></a>

    </div>


    <div id="wp" class="span4 well"><h3>Scheme blog</h3>
    <ul>
    <?php echo $this->partialLoop('partials/index/wp.phtml',$this->wp);?>
    </ul>
    </div>
</div>


