<?php 
$frontendOptions = array(
   'lifetime' => 7200,
   'debug_header' => true, // for debugging
//   'regexps' => array(
//       '^/info/sitemap/books/$' => array(              // ...but we cache the "view" action of
//           'cache' => true,                     // this ArticleController
//           'cache_with_post_variables' => true,    // and we cache even there are some variables in $_POST
//           'make_id_with_post_variables' => true,   // (but the cache will be dependent of the $_POST array)
//			'cache_id_prefix' => 'dan'       )
//   )
);
$backendOptions = array(
    'cache_dir' =>  'app/cache/fullpage'
);

// getting a Zend_Cache_Frontend_Page object
$cache = Zend_Cache::factory('Page', 'File', $frontendOptions, $backendOptions);
Zend_Debug::dump(Zend_Registry::get('page'));
Zend_Debug::dump($cache);
exit;
$cache->start();	
$site = $this->serverUrl();


$dom 	  = new DomDocument("1.0", "UTF-8");
$sitemap  = $dom->createElement('configdata');
//1st item
$nav = $dom->createElement('nav');


# News section
$news = $dom->createElement('database');
$sitemap->appendChild($nav);
$news->appendChild($dom->createElement('label', 'Database output'));
$news->appendChild($dom->createElement('uri', 'default'));
$news->appendChild($dom->createElement('changefreq', 'daily'));
$news->appendChild($dom->createElement('priority', '0.9'));
$nav->appendChild($news);
$pages = $dom->createElement('pages');
	$search = new Pas_Solr_Handler('beopublications');
	$page = Zend_Controller_Front::getInstance()->getRequest()->getParam('page');

	$params['page'] = $page;
	$params['sort'] = 'created';
	$params['direction'] = 'asc';
	$params['show'] = 1000;
    $search->setParams($params);
	$results = $search->execute();
	foreach ($results as $result) {
   	$story = $dom->createElement( 'book' .$result['id']);
	$story->appendChild($dom->createElement('label', urlencode($result['title'])));
	$story->appendChild($dom->createElement('uri', $this->serverUrl() . '/database/publications/publication/id/' . $result['id']));
	$story->appendChild($dom->createElement('changefreq','weekly'));
	$story->appendChild($dom->createElement('priority', '0.2'));
	$story->appendChild($dom->createElement('lastmod', $result['updated']));
	$pages->appendChild($story);
	}
	
			
$news->appendChild( $pages );
#end of news section

$dom->appendChild( $sitemap );

$xmlData  = $dom->saveXML();
echo $xmlData;