<?php echo '<?xml version="1.0" encoding="utf-8"?>';?>

<?php echo $this->docType();?>

<html

	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:foaf="http://xmlns.com/foaf/0.1/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:batlas="http://atlantides.org/batlas/"
	xmlns:gml="http://www.opengis.net/gml/"
	xmlns:nm="http://nomisma.org/id/"
	xmlns:ov="http://open.vocab.org/terms/"
	xmlns:owl="http://www.w3.org/2002/07/owl#"
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:skos="http://www.w3.org/2008/05/skos#"
	xmlns:pas="<?php echo $this->serverUrl();?>/database/"
	xmlns:google="http://rdf.data-vocabulary.org/#"
	xmlns:con="http://www.w3.org/2000/10/swap/pim/contact#"
	xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"
	xmlns:og="http://ogp.me/ns#"
	xmlns:fb="http://www.facebook.com/2008/fbml"
	xml:lang="en"
>
<head>

<?echo $this->headTitle(); ?>

<?echo $this->headMeta(); ?>

<?echo $this->headLink(); ?>

<?echo $this->headScript(); ?>

</head>

<body>



<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
<a class="brand" href="#">Portable Antiquities Scheme | The British Museum</a>
          <div class="nav-collapse">
	<?php echo $this->layout()->navigation ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class="container-fluid">

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">

          <div class="well sidebar-nav">

              <?php echo $this->layout()->userdata;?>

<?php echo $this->layout()->sidebar; ?>

          </div><!--/.well -->

        </div><!--/span--> <div class="span9">


          <div class="row-fluid">

            <div class="span9">
                <?php echo $this->layout()->breadcrumb;	?>
                <?php echo $this->layout()->messages;?>
                <?php echo $this->acronyms($this->layout()->content); ?>
                <?php echo $this->layout()->contexts; ?>

            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

      <hr>


    <div class="row span16 muted">

            <?php echo $this->layout()->footer; ?>

    </div>



	<?echo $this->JQuery(); ?>

	<?php echo $this->inlineScript(); ?>

	<?php echo $this->layout()->analytics; ?>

</body>

</html>