<?php
	$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
	$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/autocompleteinitPeople.js',$type='text/javascript');
	$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-datepicker.js',$type='text/javascript');
	$this->headLink()->appendStylesheet($this->baseUrl() . '/css/autocomplete.css');
	$this->headTitle('Edit find details');?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
$(document).ready(function() {
$("#datefound1").datepicker({ yearRange:'1900:<?php echo date('Y');?>'});
$("#datefound2").datepicker({ yearRange:'1900:<?php echo date('Y');?>'});

});

<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php $this->jQuery()->javascriptCaptureStart();?>
$(document).ready(function() {
       // focus on the first text input field in the first field on the page
        $("input[type='text']:first", document.forms[0]).focus();
    });
<?php $this->jQuery()->javascriptCaptureEnd();?>
<?php $this->DataEditDeleteCheck($this->find->old_findID,$this->find->createdBy);
?>
<?php echo $this->partial('partials/database/editFindH2.phtml',$this->find);?>

<?php
echo $this->form;
?>
