<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($){
$('a[rel*=lightbox]').lightBox()
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php
$this->headTitle('All finds recorded');
$this->headMeta('A list of all finds recorded on the Scheme\'s database. This
represents the rural discovery of artefacts by the public in England and Wales.',
        'description');
$this->headMeta('list,archaeological,artefacts,public,England,Wales,british museum,portable antiquities','dc.keywords');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',
        $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',
        $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
?>


<h2>All finds and coins recorded</h2>

<?php echo $this->loggedinlinks();?>

<?php if($this->params):?>
<?php echo $this->SearchParams($this->params);?>
<?php endif;?>

<?php echo $this->form;?>

<div class="row-fluid">
		
    	<?php if ($this->data): ?>
		<div class="span8">
        <?php echo $this->partialLoop('partials/database/findRecordList.phtml',$this->data);?>
        </div>
        <div class="span2">
        <?php echo $this->facetCreator($this->facets); ?>
		</div>
        <?php else:?>
    
    	<p>No records are available.

        <?php endif; ?>
        
</div>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>

