<?php $this->jQuery()->javascriptCaptureStart() ?>
jQuery(document).ready(function($){
$('a[rel*=lightbox]').lightBox()
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<?php
$this->headTitle('All finds recorded');
$this->headMeta('A list of all finds recorded on the Scheme\'s database. This
represents the rural discovery of artefacts by the public in England and Wales.',
        'description');
$this->headMeta('list,archaeoligical,artefacts,public,England,Wales,british museum,portable antiquities','dc.keywords');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.lightbox.js',
        $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',
        $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css')
?>


<h2>All finds and coins recorded</h2>

<?php echo $this->loggedinlinks();?>

<?php if($this->params):?>
<?php echo $this->SearchParams($this->params);?>
<?php endif;?>
<?php echo $this->form;?>
<div id="findsList">
<?php if ($this->data): ?>
<table class="stripeMe" summary="A complete list of finds and coins recorded">
<caption>A complete list of all finds recorded</caption>
<thead>
<tr>
<th>Image</th>
<th>Object Type</th>
<th>Find number</th>
<th>Broadperiod</th>
<th>County</th>
<th>Actions</th>
</tr>
</thead>

<tbody>
<?php echo $this->partialLoop('partials/database/findsTable2.phtml',$this->data);?>
</tbody>
</table>
<?php else:?>
    <p>No records are available.
<?php endif; ?>


<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
</div>
