<div class="row-fluid" id="prior-next">
    <ul class="pager">

        <?php if(count($this->recordsprior)) :?>
		<?php echo $this->partial('partials/database/previous.phtml', $this->recordsprior['0']) ;?>
	<?php endif;?>

        <?php if(count($this->nexts)) :?>
		<?php echo $this->partial('partials/database/next.phtml', $this->nexts['0']) ;?>
	<?php endif;?>
    </ul>
</div>

<div class="row-fluid">
<div typeof="pas:record" about="<?php echo $this->finds['0']['old_findID'];?>">

    <?php
	echo $this->partialLoop('partials/database/recordheadtitle.phtml',$this->finds);
	$this->meta();
	echo $this->partialLoop('partials/database/zoterorecord.phtml',$this->finds);
    ?>



<div id="workflowstatus"></div>

</div>

<div class="row-fluid">

	<div class="span8">
	<?php
	echo $this->partial('partials/database/recordh2section.phtml',$this->finds['0']);
	echo $this->notifyFloPublic(
                $this->finds['0']['institution'],
 		$this->finds['0']['id'],
                $this->finds['0']['secwfstage']
                );
       	echo $this->partialLoop('partials/database/recorddescriptive.phtml',$this->finds);
	echo $this->partial('partials/database/treasurefinddetails.phtml', $this->finds['0']);
	echo $this->partial('partials/database/temporal.phtml', $this->temporals['0']);
	if (count($this->findsdata) > 0) {
	echo $this->partialLoop('partials/database/dimensions.phtml', $this->findsdata);
	}

        echo $this->partial('partials/database/datefound.phtml',$this->finds['0']);

        if (count($this->rallyfind)){
            echo $this->partialLoop('partials/database/rallyfind.phtml', $this->rallyfind);
        }

        if (count($this->peoples) > 0):
        ?>

        <h3>Personal details</h3>
	<?php echo $this->partialLoop('partials/database/personal.phtml', $this->peoples) ?>
	<?php endif;?>

        <?php
        if ($this->findotherrefs){
            echo $this->partialLoop('partials/database/otherrefs.phtml', $this->findotherrefs);
        }
        if (count($this->findsmaterial)){
            echo $this->partialLoop('partials/database/materials.phtml', $this->findsmaterial);
        }
        echo $this->coinDataDisplay(
            $this->finds['0']['objecttype'],
            $this->finds['0']['broadperiod'],
            $this->coins,
            $this->finds);

        if(count($this->coinrefs)):?>
        <div id="coinrefslinked">
        <h3>Coin references</h3>
        <ul>
        <?php echo $this->partialLoop('partials/numismatics/coinrefs.phtml',$this->coinrefs);?>
        </ul>
        
        <?php
        echo $this->CoinRefAddLink(
                $this->finds['0']['old_findID'],
                $this->finds['0']['id'],
                $this->finds['0']['broadperiod'],
                $this->finds['0']['secuid'],
                $this->finds['0']['id'],
                $this->finds['0']['createdBy']);
        ?>
        </div>
<?php else:?>
<div id="coinrefs">
<h3>Coin references</h3>
<p>No coin references available.</p>
<?php
echo $this->CoinRefAddLink(
        $this->finds['0']['old_findID'],
        $this->finds['0']['id'],
        $this->finds['0']['broadperiod'],
        $this->finds['0']['secuid'],
        $this->finds['0']['id'],
        $this->finds['0']['createdBy']);
?>
</div>
<?php endif;?>

	</div>

	<div class="span3 well" id="imagepane">
		<?php
		if (count($this->thumbs) > 0){
		echo $this->partialLoop('partials/database/thumbs.phtml', $this->thumbs);
		} else {?>
		<p>There are currently no images available.<br/>
		Do you own this object, send us a picture!</p>
		<?php
		}
		?>
		<?php
		echo $this->ImageLink($this->finds['0']['old_findID'],$this->finds['0']['id'],$this->finds['0']['secuid'],$this->finds['0']['createdBy']);
		?>
	</div>
<div class="span3 well" id="qrcode">
<h3>QR barcode</h3>
<img class="flow" src="http://chart.apis.google.com/chart?chs=150x150&amp;cht=qr&amp;chl=<?php echo $this->CurUrl();?>" alt="QR code for this URL" width="150" height="150" style="float:right;"/>
<p>The barcode on the right is a unique identifier for this record. If your phone has scanning software installed, then this can be used for sharing or you can print it off and attach it to the object.</p>
</div>
</div>

<div class="row-fluid">
<?php if (count($this->findspots)) : ?>
<?php echo $this->Findspot($this->findspots);?>
<?php else: ?>
<div id="findspotdata">
<h3>Spatial data</h3>
<p>No data recorded at present.</p>
<?php echo $this->FindSpotLink(
        $this->finds['0']['old_findID'],
        $this->finds['0']['id'],
        $this->finds['0']['secuid'],
        $this->finds['0']['createdBy']);?>
</div>
<?php endif; ?>

</div>
<div class="row-fluid">
<h3>References cited</h3>
<div id="references">
<?php
if (count($this->refs) > 0) : ?>
<p>
    <?php echo $this->AddRefLink(
        $this->finds['0']['old_findID'],
        $this->finds['0']['id'],
        $this->finds['0']['secuid'],
        $this->finds['0']['createdBy']);?>
</p>

<ul id="related">
<?php echo $this->partialLoop('partials/database/harvardbook.phtml', $this->refs);?>
</ul>
<?php else:?>
<p class="norefs">No references cited so far.</p>

<?php echo $this->AddRefLink($this->finds['0']['old_findID'],$this->finds['0']['id'],
$this->finds['0']['secuid'],$this->finds['0']['createdBy']);?>
<?php endif;?>
</div>
</div>

<?php
	echo $this->moreLikeThis('old_findID:' . $this->finds['0']['old_findID']);
?>

</div>


<p>
<a class="btn btn-small" href="<?php echo $this->url(array('module' => 'database','controller' => 'artefacts','action' => 'errorreport'));?>" title="Send message to the allotted National Finds Adviser">Spotted a mistake? Tell us.</a> | <?php if(count($this->comments) <= 0) : ?>

<a class="btn btn-small" href="#comment_content" id="addcomment" title="Comment on this artefact's record">Be the first to comment</a></p>
<?php else: ?>
<a class="btn btn-small" href="#comment_content" id="addcomment" title="Comment on this find">Add a new comment</a> | Total Comments [<?php echo count($this->comments);?>]</p><h3>Approved comments on this record</h3>
<?php endif;?>
<div id="comm">
<?php if($this->comments):?>
<ul>
<?php echo $this->partialLoop('partials/database/comments.phtml', $this->comments) ;?>
</ul>
<?php endif;?>
</div>


<div id="commentform">

<div>
<h2>Comment on this artefact's record</h2>
<div id="data">
<p>Data entered via this form is checked against the <a href="http://akismet.com/" title="The Aksimet anti-spam detection service">akismet</a> service to recognise spam.</p>

<?php
$auth = Zend_Registry::get('auth');
if($auth->hasIdentity())
{
$user = $auth->getIdentity();
$this->form->comment_author->setValue($user->fullname);
$this->form->comment_author_email->setValue($user->email);

}
echo $this->form;
?>

</div>
<div class="row-fluid">
<?php

	echo $this->partial('partials/database/recordaudit.phtml',$this->finds['0']);
?>


	<ul id="tab" class="nav nav-tabs">
            <li class="active"><a href="#find" data-toggle="tab">Finds audit</a></li>
            <li><a href="#fspot" data-toggle="tab">Findspot audit</a></li>
            <li><a href="#coin" data-toggle="tab">Numismatic audit</a></li>
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="find">
			<?php echo $this->ChangesFind($this->finds['0']['id']);?>
			</div>
            <div class="tab-pane fade" id="fspot">
			<?php  echo $this->ChangesFindSpot($this->finds['0']['id']);?>
			</div>
            <div class="tab-pane fade" id="coin">
			<?php echo $this->ChangesCoins($this->finds['0']['id']);?>
			</div>
          </div>
	</div>
</div>
</div>