<?php 
$this->headScript()->appendFile($this->baseUrl().'/js/JQuery/ui.datepicker.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/ui.datepicker.css');
$this->headTitle('Add a new volunteer role');
?>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
$("#live").datepicker({ maxDate: '+1y'});
$("#expire").datepicker({ maxDate: '+1y' });
});
<?php $this->headScript()->captureEnd() ?>
<h2>Add a volunteer role</h2>
<?php 
echo $this->form;
?>