<?php
$this->headTitle('Country analytical data provided via Google Analytics');
?>
<h2><?php echo $this->title();?></h2>
<p>
<?php 
$timespans = array(
'this week' => 'thisweek',
'last week' => 'lastweek',
'this month' => 'thismonth',
'last month' => 'lastmonth',
'this year' => 'thisyear',
'last year' => 'lastyear'
);
foreach($timespans as $k => $v):
?>
<a class="btn btn-small" href="<?php echo $this->url(array('module' => 'analytics','controller' => 'visitors','action' => 'mobile', 'timespan' => $v),'default',false);?>"><?php echo ucfirst($k);?></a>
<?php endforeach;?> 

</p>
<table class="table table-striped">
	<caption>Visitors over the timespan of: </caption>
		<thead>
		<tr>
			
			<th>Branding</th>
			<th>Model</th>
			<th>Info</th>
			<th>Visitors</th>
		</tr>
		</thead>
		<tbody>
			<?php foreach($this->results as $row):?>
			<tr>
				<td><?php echo $row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_MOBILE_DEVICE_BRANDING)->value;?></td>
				<td><?php echo $row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_MOBILE_DEVICE_MODEL)->value;?></td>
				<td><?php echo $row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_MOBILE_DEVICE_INFO)->value;?></td>
				<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value;?></td>
			</tr>
			<?php endforeach;?>
		</tbody>
</table>