<?php
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinitpeople1.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css');
$this->headTitle('User administration section');
?>

<h2>User administration</h2>
<?php
echo $this->Href(array('module' => 'admin','controller'=>'users', 'action'=>'add', 'checkAcl'=>true,
'acl'=>'Zend_Acl', 'wrapper' => array('tag' => 'p'),
'content'=>'Add an account','attribs' => array('title' => 'Add a new user','class' => 'btn btn-large btn-danger')));
?>

<div id="findsList">
<?php if ($this->paginator): ?>

<table class="table table-striped " summary="List of users registered on the database">
<caption>All users</caption>
	<thead>
	<tr>
		<th>Username</th>
		<th>Fullname</th>
		<th>Role assigned</th>
		<th>Last login</th>
		<th>Visits</th>
		<th>Actions</th>
	</tr>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('partials/admin/userAdminTable.phtml',$this->paginator);?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'structure/pagination.phtml'); ?>
<?php else:?>
<p>There are no users available with those criteria.</p>
<?php endif; ?>
</div>
